[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
thiserror = "2.0.20"
serde_json = { features = [
	"preserve_order",
	"unbounded_depth",
], version = "1.0.151" }

[workspace.package]
authors = ["Davy Duperron <yamafaktory@gmail.com>"]
categories = ["command-line-utilities", "filesystem"]
edition = "2024"
keywords = ["cli", "json", "terminal", "tool", "query"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/yamafaktory/jql"
rust-version = "1.88"
version = "9.0.0"

[workspace.lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = { level = "deny", priority = -1 }
redundant_lifetimes = "warn"
unit_bindings = "warn"
unreachable_pub = "warn"
unsafe_code = "deny"
unused_qualifications = "warn"

[workspace.lints.clippy]
all = "deny"

# https://github.com/rust-lang/cargo/issues/8264
[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
