[package]
authors.workspace = true
categories.workspace = true
description = "jql - JSON Query Language - is a fast and simple command-line tool to manipulate JSON data."
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "jql"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
colored_json = { version = "5.0.0" }
jql-runner = { path = "../jql-runner", version = "9.0.2" }
serde_json.workspace = true

[target.'cfg(not(target_arch = "loongarch64"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ name }-v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
