name: performance

on:
  pull_request:
  schedule:
    - cron: "00 01 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install hyperfine and jql - jq is already available!
        run: cargo install hyperfine && cargo install jql
      - name: Run performance benchmarks
        run: ./performance.sh
      - name: Commit to pull-request branch
        run: |
          git config --global user.name 'yamafaktory'
          git config --global user.email 'yamafaktory@gmail.com'
          git commit -am "chore(performance): update benchmarks"
          git push
