name: performance

on:
  pull_request:
  schedule:
    - cron: "00 01 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run performance benchmarks
        run: ./performance.sh